version: "2.4"
services:
  crossdev:
    container_name: crossdev
    hostname: crossdev
    image: ${IMAGE:-crossdev}
    extends:
      file: ./yaml/crossdev.yml
      service: crossdev
    build:
      args:
        - SSH_PORT=${SSH_PORT:?err}
        - GIT_USER_NAME=${GIT_USER_NAME:?err}
        - GIT_USER_MAIL=${GIT_USER_MAIL:?err}
        - UID=${UID:-1000}
        - USER_NAME=${USER_NAME:?err}
        - USER_HOME=${USER_HOME:?err}
        - GID=${GID:-1000}
        - GROUP_NAME=${GROUP_NAME:-staff}
        - VSCODE_VERSION=${VSCODE_VERSION}
    ports:
      - "${BIND_IP:-127.0.0.1}:${SSH_PORT:?err}:${SSH_PORT:?err}"
    volumes:
      - "./data/ssh/hostkey:/etc/ssh/hostkey"
